### ISSUE TITLE
Wrap sd_listen_fds

### ISSUE THREAD

**Issue by daurnimator** [daurnimator/lua-systemd#6]
Requested by @zash

**Comment by Zash** [comment]
> Internally, sd_listen_fds() checks whether the $LISTEN_PID environment variable equals the daemon PID. If not, it returns immediately.

That, and being able to unset that variable, is what it does over `os.getenv()`.

Exposing `SD_LISTEN_FDS_START` would also be good, so you don't have to guess that it's 3.

**Comment by daurnimator** [comment]
> Exposing SD_LISTEN_FDS_START would also be good, so you don't have to guess that it's 3.

It already is. `systemd.daemon.LISTEN_FDS_START`
