### ISSUE TITLE
fatal error: systemd/sd-daemon.h: file or directory not found

### ISSUE THREAD

**Issue by verymilan** [daurnimator/lua-systemd#7]
Hi there i just ran into the following error:

```
src/daemon.c:8:31: fatal error: systemd/sd-daemon.h: file or directory not found
 #include <systemd/sd-daemon.h>
                               ^
compilation terminated.

Error: Build error: Failed compiling object src/daemon.o
```

**Comment by danielsilverstone-ct** [comment]
Have you got the systemd library headers installed?

**Comment by verymilan** [comment]
Ah, okey just installed `libsystemd-dev` (debian) and the comilation succeed, thank you.
A note at the readme would be awesome. :)

**Comment by njucjc** [comment]
What can I deal with this problem on MacOS

**Comment by daurnimator** [comment]
> What can I deal with this problem on MacOS

This library should only be used on systemd-based systems.... which doesn't include MacOS.

**Comment by MiladSniper** [comment]
> Ah, okey just installed `libsystemd-dev` (debian) and the comilation succeed, thank you.
> A note at the readme would be awesome. :)

should Install systemd-devel on CentOS 8
